### ISSUE TITLE
Banpools page should say antispam is only public banpool

### ISSUE THREAD

**Issue by AyuAi** [BeemoBot/docs.beemo.gg#10]
The banpool page mentions the antispam banpool, but it could further clarify that the antispam banpool is the only publicly available one.

**Comment by rubenalamina** [comment]
> The banpool page mentions the antispam banpool, but it could further clarify that the antispam banpool is the only publicly available one.

Do you have information about this public banpool? We just added Beemo to our server to see how it works but I can't find any information about the list, lists or resources used to do what it supposedly does.

**Comment by AyuAi** [comment]
> > The banpool page mentions the antispam banpool, but it could further clarify that the antispam banpool is the only publicly available one.
> 
> Do you have information about this public banpool? We just added Beemo to our server to see how it works but I can't find any information about the list, lists or resources used to do what it supposedly does.

Type `/banpool info antispam` in your server

**Comment by wasdennnoch** [comment]
Banpools have been removed as of #26 so this is not needed anymore.
