### ISSUE TITLE
Site: links point to incorrect docs locations

### ISSUE THREAD

**Issue by Blooym** [BeemoBot/docs.beemo.gg#8]
## About
On [Beemo's subscribe page](https://beemo.gg/subscribe/). the highlighted documentation links point to the incorrect places without their nesting categories in the url and don't work. Unsure if this was known so wanted to open an issue to make sure.

## Suggested Fix

Change beemo.gg/subscribe links to have their nesting categories, eg.

`docs.beemo.gg/honey` -> `docs.beemo.gg/utility/honey`

**Comment by AyuAi** [comment]
What if we just un-nest the links? I feel as though Beemo has a small enough utility set to warrant them being individualized 👀

**Comment by AngelNull** [comment]
It all goes down to how you want the pages structured, I think both ways will look clean

**Comment by wasdennnoch** [comment]
As part of the new website design the links have been updated to link to the correct pages. IMO the nesting is fine as-is, especially once we (finally) add some more documentaion for stuff.
